# config/services_test.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Tests\Doubles\LlmClientStub:
        public: true

    App\Tests\Doubles\LlmClientSpy:
        public: true

    # КЛЮЧЕВОЕ: контейнер будет отдавать наш стаб при запросе интерфейса
    App\Service\AI\LlmClient: '@App\Tests\Doubles\LlmClientStub'


    # Тестовый билдер сущностей (если есть), делаем публичным
    App\Tests\Build\TestEntityBuilder:
        public: true
