# Enable stateless CSRF protection for forms and logins/logouts
framework:
    form:
        csrf_protection:
            token_id: submit

    # see: https://github.com/symfony/symfony/issues/59065
    #csrf_protection:
    #    stateless_token_ids:
    #        - submit
    #        - authenticate
    #        - logout
